#dockerid：https://hub.docker.com/の自分DockerId(ログインID)で切り替えください
version: '2'
services:
    db:
        image: mysql:5.6
        ports:
            - "3306:3306"
        volumes:
            - ./database/sql/init/:/docker-entrypoint-initdb.d
            - ./database/sql/config/:/etc/mysql/conf.d
        environment:
            MYSQL_DATABASE: mydb
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            MYSQL_ROOT_PASSWORD: hoge
    app:
        image: motikan2010/centos7_php7:latest
        depends_on: 
            - db
        ports:
            - "8080:8080"
        #ソースコードフォルダをマウント
        volumes:
            - .:/var/www/app
